// Code generated by protoc-gen-go.
// source: service.proto
// DO NOT EDIT!

/*
Package nodes is a generated protocol buffer package.

It is generated from these files:
	service.proto

It has these top-level messages:
	File
	NoReply
	CreateRequest
	SetTitleRequest
	SetNotesRequest
	AddFilesRequest
	RemoveFilesRequest
	GetRequest
	GetReply
*/
package nodes

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type NodeType int32

const (
	NodeType_UNKNOWN NodeType = 0
	NodeType_DATA    NodeType = 1
	NodeType_COMPUTE NodeType = 2
	NodeType_MANUAL  NodeType = 3
	NodeType_FINDING NodeType = 4
)

var NodeType_name = map[int32]string{
	0: "UNKNOWN",
	1: "DATA",
	2: "COMPUTE",
	3: "MANUAL",
	4: "FINDING",
}
var NodeType_value = map[string]int32{
	"UNKNOWN": 0,
	"DATA":    1,
	"COMPUTE": 2,
	"MANUAL":  3,
	"FINDING": 4,
}

func (x NodeType) String() string {
	return proto.EnumName(NodeType_name, int32(x))
}
func (NodeType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type File struct {
	// ID of the file stored in the data service.
	Id string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	// Local name of the file.
	Name string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
}

func (m *File) Reset()                    { *m = File{} }
func (m *File) String() string            { return proto.CompactTextString(m) }
func (*File) ProtoMessage()               {}
func (*File) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *File) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *File) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type NoReply struct {
}

func (m *NoReply) Reset()                    { *m = NoReply{} }
func (m *NoReply) String() string            { return proto.CompactTextString(m) }
func (*NoReply) ProtoMessage()               {}
func (*NoReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type CreateRequest struct {
	// ID is provided by caller.
	Id      string   `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Project string   `protobuf:"bytes,2,opt,name=project" json:"project,omitempty"`
	Type    NodeType `protobuf:"varint,3,opt,name=type,enum=nodes.NodeType" json:"type,omitempty"`
	Title   string   `protobuf:"bytes,4,opt,name=title" json:"title,omitempty"`
	Account string   `protobuf:"bytes,5,opt,name=account" json:"account,omitempty"`
}

func (m *CreateRequest) Reset()                    { *m = CreateRequest{} }
func (m *CreateRequest) String() string            { return proto.CompactTextString(m) }
func (*CreateRequest) ProtoMessage()               {}
func (*CreateRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *CreateRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *CreateRequest) GetProject() string {
	if m != nil {
		return m.Project
	}
	return ""
}

func (m *CreateRequest) GetType() NodeType {
	if m != nil {
		return m.Type
	}
	return NodeType_UNKNOWN
}

func (m *CreateRequest) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *CreateRequest) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

type SetTitleRequest struct {
	Id      string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Project string `protobuf:"bytes,2,opt,name=project" json:"project,omitempty"`
	Title   string `protobuf:"bytes,3,opt,name=title" json:"title,omitempty"`
	Account string `protobuf:"bytes,5,opt,name=account" json:"account,omitempty"`
}

func (m *SetTitleRequest) Reset()                    { *m = SetTitleRequest{} }
func (m *SetTitleRequest) String() string            { return proto.CompactTextString(m) }
func (*SetTitleRequest) ProtoMessage()               {}
func (*SetTitleRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *SetTitleRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *SetTitleRequest) GetProject() string {
	if m != nil {
		return m.Project
	}
	return ""
}

func (m *SetTitleRequest) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *SetTitleRequest) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

type SetNotesRequest struct {
	Id      string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Project string `protobuf:"bytes,2,opt,name=project" json:"project,omitempty"`
	Notes   string `protobuf:"bytes,3,opt,name=notes" json:"notes,omitempty"`
	Account string `protobuf:"bytes,5,opt,name=account" json:"account,omitempty"`
}

func (m *SetNotesRequest) Reset()                    { *m = SetNotesRequest{} }
func (m *SetNotesRequest) String() string            { return proto.CompactTextString(m) }
func (*SetNotesRequest) ProtoMessage()               {}
func (*SetNotesRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *SetNotesRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *SetNotesRequest) GetProject() string {
	if m != nil {
		return m.Project
	}
	return ""
}

func (m *SetNotesRequest) GetNotes() string {
	if m != nil {
		return m.Notes
	}
	return ""
}

func (m *SetNotesRequest) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

type AddFilesRequest struct {
	Id      string  `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Project string  `protobuf:"bytes,2,opt,name=project" json:"project,omitempty"`
	Files   []*File `protobuf:"bytes,3,rep,name=files" json:"files,omitempty"`
	Account string  `protobuf:"bytes,5,opt,name=account" json:"account,omitempty"`
}

func (m *AddFilesRequest) Reset()                    { *m = AddFilesRequest{} }
func (m *AddFilesRequest) String() string            { return proto.CompactTextString(m) }
func (*AddFilesRequest) ProtoMessage()               {}
func (*AddFilesRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *AddFilesRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *AddFilesRequest) GetProject() string {
	if m != nil {
		return m.Project
	}
	return ""
}

func (m *AddFilesRequest) GetFiles() []*File {
	if m != nil {
		return m.Files
	}
	return nil
}

func (m *AddFilesRequest) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

type RemoveFilesRequest struct {
	Id      string   `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Project string   `protobuf:"bytes,2,opt,name=project" json:"project,omitempty"`
	FileIds []string `protobuf:"bytes,3,rep,name=file_ids,json=fileIds" json:"file_ids,omitempty"`
	Account string   `protobuf:"bytes,5,opt,name=account" json:"account,omitempty"`
}

func (m *RemoveFilesRequest) Reset()                    { *m = RemoveFilesRequest{} }
func (m *RemoveFilesRequest) String() string            { return proto.CompactTextString(m) }
func (*RemoveFilesRequest) ProtoMessage()               {}
func (*RemoveFilesRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *RemoveFilesRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *RemoveFilesRequest) GetProject() string {
	if m != nil {
		return m.Project
	}
	return ""
}

func (m *RemoveFilesRequest) GetFileIds() []string {
	if m != nil {
		return m.FileIds
	}
	return nil
}

func (m *RemoveFilesRequest) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

type GetRequest struct {
	Id      string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Project string `protobuf:"bytes,2,opt,name=project" json:"project,omitempty"`
}

func (m *GetRequest) Reset()                    { *m = GetRequest{} }
func (m *GetRequest) String() string            { return proto.CompactTextString(m) }
func (*GetRequest) ProtoMessage()               {}
func (*GetRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *GetRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *GetRequest) GetProject() string {
	if m != nil {
		return m.Project
	}
	return ""
}

type GetReply struct {
	// ID of the node.
	Id string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	// Type of node
	Type NodeType `protobuf:"varint,2,opt,name=type,enum=nodes.NodeType" json:"type,omitempty"`
	// Title/description of the node.
	Title string `protobuf:"bytes,3,opt,name=title" json:"title,omitempty"`
	// Long-form notes.
	Notes string  `protobuf:"bytes,4,opt,name=notes" json:"notes,omitempty"`
	Files []*File `protobuf:"bytes,5,rep,name=files" json:"files,omitempty"`
}

func (m *GetReply) Reset()                    { *m = GetReply{} }
func (m *GetReply) String() string            { return proto.CompactTextString(m) }
func (*GetReply) ProtoMessage()               {}
func (*GetReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *GetReply) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *GetReply) GetType() NodeType {
	if m != nil {
		return m.Type
	}
	return NodeType_UNKNOWN
}

func (m *GetReply) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *GetReply) GetNotes() string {
	if m != nil {
		return m.Notes
	}
	return ""
}

func (m *GetReply) GetFiles() []*File {
	if m != nil {
		return m.Files
	}
	return nil
}

func init() {
	proto.RegisterType((*File)(nil), "nodes.File")
	proto.RegisterType((*NoReply)(nil), "nodes.NoReply")
	proto.RegisterType((*CreateRequest)(nil), "nodes.CreateRequest")
	proto.RegisterType((*SetTitleRequest)(nil), "nodes.SetTitleRequest")
	proto.RegisterType((*SetNotesRequest)(nil), "nodes.SetNotesRequest")
	proto.RegisterType((*AddFilesRequest)(nil), "nodes.AddFilesRequest")
	proto.RegisterType((*RemoveFilesRequest)(nil), "nodes.RemoveFilesRequest")
	proto.RegisterType((*GetRequest)(nil), "nodes.GetRequest")
	proto.RegisterType((*GetReply)(nil), "nodes.GetReply")
	proto.RegisterEnum("nodes.NodeType", NodeType_name, NodeType_value)
}

func init() { proto.RegisterFile("service.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 466 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x94, 0xcd, 0x6e, 0xd3, 0x40,
	0x10, 0xc7, 0xf1, 0x57, 0xec, 0x4c, 0xd4, 0xc4, 0xac, 0x2a, 0xe4, 0xf6, 0x14, 0xc2, 0x25, 0xf4,
	0x90, 0x43, 0x90, 0x10, 0x57, 0xab, 0xa5, 0x51, 0x04, 0xdd, 0x22, 0x37, 0x11, 0x47, 0x14, 0xbc,
	0x83, 0x64, 0x70, 0xbd, 0xc6, 0xde, 0x56, 0xf8, 0x25, 0x78, 0x20, 0x9e, 0x0e, 0xed, 0xfa, 0x03,
	0xb7, 0x26, 0x51, 0x93, 0x9b, 0x67, 0xc6, 0xff, 0xf9, 0xad, 0x67, 0xff, 0x63, 0x38, 0xca, 0x31,
	0xbb, 0x8f, 0x42, 0x9c, 0xa5, 0x19, 0x17, 0x9c, 0x58, 0x09, 0x67, 0x98, 0x4f, 0xce, 0xc0, 0xbc,
	0x8c, 0x62, 0x24, 0x43, 0xd0, 0x23, 0xe6, 0x69, 0x63, 0x6d, 0xda, 0x0f, 0xf4, 0x88, 0x11, 0x02,
	0x66, 0xb2, 0xb9, 0x45, 0x4f, 0x57, 0x19, 0xf5, 0x3c, 0xe9, 0x83, 0x4d, 0x79, 0x80, 0x69, 0x5c,
	0x4c, 0x7e, 0x6b, 0x70, 0x74, 0x9e, 0xe1, 0x46, 0x60, 0x80, 0x3f, 0xef, 0x30, 0x17, 0x9d, 0x06,
	0x1e, 0xd8, 0x69, 0xc6, 0xbf, 0x63, 0x28, 0xaa, 0x1e, 0x75, 0x48, 0x5e, 0x81, 0x29, 0x8a, 0x14,
	0x3d, 0x63, 0xac, 0x4d, 0x87, 0xf3, 0xd1, 0x4c, 0x1d, 0x64, 0x46, 0x39, 0xc3, 0x55, 0x91, 0x62,
	0xa0, 0x8a, 0xe4, 0x18, 0x2c, 0x11, 0x89, 0x18, 0x3d, 0x53, 0x89, 0xcb, 0x40, 0x36, 0xdd, 0x84,
	0x21, 0xbf, 0x4b, 0x84, 0x67, 0x95, 0x4d, 0xab, 0x70, 0xf2, 0x03, 0x46, 0x37, 0x28, 0x56, 0xf2,
	0xad, 0xfd, 0x4f, 0xd4, 0xc0, 0x8c, 0x7d, 0x60, 0x94, 0x0b, 0xcc, 0x0f, 0x82, 0x25, 0x52, 0x59,
	0xc3, 0x54, 0xb0, 0x03, 0xf6, 0x0b, 0x46, 0x3e, 0x63, 0xf2, 0x92, 0x0e, 0x80, 0xbd, 0x04, 0xeb,
	0x9b, 0x54, 0x7a, 0xc6, 0xd8, 0x98, 0x0e, 0xe6, 0x83, 0x6a, 0xd8, 0xb2, 0x5b, 0x50, 0x56, 0x76,
	0x90, 0x73, 0x20, 0x01, 0xde, 0xf2, 0x7b, 0x3c, 0x10, 0x7e, 0x02, 0x8e, 0x44, 0x7c, 0x89, 0x58,
	0xc9, 0xef, 0x07, 0xb6, 0x8c, 0x97, 0x6c, 0x17, 0xf4, 0x2d, 0xc0, 0x02, 0xc5, 0xde, 0x30, 0xe9,
	0x48, 0x47, 0x09, 0xd3, 0xb8, 0xe8, 0xc8, 0x6a, 0xcb, 0xe9, 0x4f, 0xb2, 0xdc, 0x03, 0x17, 0x34,
	0xd7, 0x65, 0xb6, 0xaf, 0xab, 0x99, 0xab, 0xb5, 0x6d, 0xae, 0x67, 0x0b, 0x70, 0x6a, 0x00, 0x19,
	0x80, 0xbd, 0xa6, 0x1f, 0xe8, 0xf5, 0x67, 0xea, 0x3e, 0x23, 0x0e, 0x98, 0x17, 0xfe, 0xca, 0x77,
	0x35, 0x99, 0x3e, 0xbf, 0xbe, 0xfa, 0xb4, 0x5e, 0xbd, 0x77, 0x75, 0x02, 0xd0, 0xbb, 0xf2, 0xe9,
	0xda, 0xff, 0xe8, 0x1a, 0xb2, 0x70, 0xb9, 0xa4, 0x17, 0x4b, 0xba, 0x70, 0xcd, 0xf9, 0x1f, 0x1d,
	0xec, 0x9b, 0x72, 0x77, 0xc9, 0x0c, 0x7a, 0xe5, 0xda, 0x91, 0xe3, 0x0a, 0xf9, 0x60, 0x0b, 0x4f,
	0x87, 0xcd, 0xa7, 0x95, 0x83, 0x98, 0x83, 0x53, 0xaf, 0x05, 0x79, 0x51, 0xd5, 0x1e, 0xed, 0xc9,
	0x16, 0x8d, 0x72, 0x77, 0x5b, 0xd3, 0xb6, 0xfb, 0xff, 0x34, 0xb5, 0x49, 0x1b, 0xcd, 0x23, 0xd7,
	0x76, 0x34, 0xef, 0x60, 0xd0, 0xb2, 0x17, 0x39, 0xa9, 0xca, 0x5d, 0xcb, 0x75, 0x94, 0xaf, 0xc1,
	0x58, 0xa0, 0x20, 0xcf, 0xab, 0xf4, 0x3f, 0xbf, 0x9c, 0x8e, 0xda, 0xa9, 0x34, 0x2e, 0xbe, 0xf6,
	0xd4, 0xdf, 0xee, 0xcd, 0xdf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x74, 0x1a, 0x2b, 0x33, 0xfe, 0x04,
	0x00, 0x00,
}
