version: "2"

services:
  nats:
    image: nats
    restart: always
    ports:
      - 4222:4222
      - 8222:8222

  mongo:
    image: mongo:3.4.5
    restart: always
    ports:
      - 27017:27017
    command: --storageEngine wiredTiger

  account:
    image: quay.io/rdm-academy/account
    command: -nats.addr nats:4222
    restart: always
    depends_on:
      - nats
