// Code generated by protoc-gen-go.
// source: service.proto
// DO NOT EDIT!

/*
Package account is a generated protocol buffer package.

It is generated from these files:
	service.proto

It has these top-level messages:
	CreateUserRequest
	CreateUserResponse
	GetUserRequest
	GetUserResponse
	DeleteUserRequest
	DeleteUserResponse
*/
package account

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type CreateUserRequest struct {
	Issuer  string `protobuf:"bytes,1,opt,name=issuer" json:"issuer,omitempty"`
	Subject string `protobuf:"bytes,2,opt,name=subject" json:"subject,omitempty"`
	Name    string `protobuf:"bytes,3,opt,name=name" json:"name,omitempty"`
	Email   string `protobuf:"bytes,4,opt,name=email" json:"email,omitempty"`
}

func (m *CreateUserRequest) Reset()                    { *m = CreateUserRequest{} }
func (m *CreateUserRequest) String() string            { return proto.CompactTextString(m) }
func (*CreateUserRequest) ProtoMessage()               {}
func (*CreateUserRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *CreateUserRequest) GetIssuer() string {
	if m != nil {
		return m.Issuer
	}
	return ""
}

func (m *CreateUserRequest) GetSubject() string {
	if m != nil {
		return m.Subject
	}
	return ""
}

func (m *CreateUserRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CreateUserRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

type CreateUserResponse struct {
	Id    string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Name  string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Email string `protobuf:"bytes,3,opt,name=email" json:"email,omitempty"`
}

func (m *CreateUserResponse) Reset()                    { *m = CreateUserResponse{} }
func (m *CreateUserResponse) String() string            { return proto.CompactTextString(m) }
func (*CreateUserResponse) ProtoMessage()               {}
func (*CreateUserResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *CreateUserResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *CreateUserResponse) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CreateUserResponse) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

type GetUserRequest struct {
	Id    string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Name  string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Email string `protobuf:"bytes,3,opt,name=email" json:"email,omitempty"`
}

func (m *GetUserRequest) Reset()                    { *m = GetUserRequest{} }
func (m *GetUserRequest) String() string            { return proto.CompactTextString(m) }
func (*GetUserRequest) ProtoMessage()               {}
func (*GetUserRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *GetUserRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *GetUserRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *GetUserRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

type GetUserResponse struct {
	Id    string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Name  string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Email string `protobuf:"bytes,3,opt,name=email" json:"email,omitempty"`
}

func (m *GetUserResponse) Reset()                    { *m = GetUserResponse{} }
func (m *GetUserResponse) String() string            { return proto.CompactTextString(m) }
func (*GetUserResponse) ProtoMessage()               {}
func (*GetUserResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *GetUserResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *GetUserResponse) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *GetUserResponse) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

type DeleteUserRequest struct {
	Id string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
}

func (m *DeleteUserRequest) Reset()                    { *m = DeleteUserRequest{} }
func (m *DeleteUserRequest) String() string            { return proto.CompactTextString(m) }
func (*DeleteUserRequest) ProtoMessage()               {}
func (*DeleteUserRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *DeleteUserRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type DeleteUserResponse struct {
}

func (m *DeleteUserResponse) Reset()                    { *m = DeleteUserResponse{} }
func (m *DeleteUserResponse) String() string            { return proto.CompactTextString(m) }
func (*DeleteUserResponse) ProtoMessage()               {}
func (*DeleteUserResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func init() {
	proto.RegisterType((*CreateUserRequest)(nil), "account.CreateUserRequest")
	proto.RegisterType((*CreateUserResponse)(nil), "account.CreateUserResponse")
	proto.RegisterType((*GetUserRequest)(nil), "account.GetUserRequest")
	proto.RegisterType((*GetUserResponse)(nil), "account.GetUserResponse")
	proto.RegisterType((*DeleteUserRequest)(nil), "account.DeleteUserRequest")
	proto.RegisterType((*DeleteUserResponse)(nil), "account.DeleteUserResponse")
}

func init() { proto.RegisterFile("service.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 266 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x92, 0xbd, 0x4e, 0xc3, 0x30,
	0x14, 0x85, 0x95, 0xb4, 0x34, 0xe2, 0x48, 0x14, 0xf5, 0xaa, 0x02, 0x2b, 0x2c, 0x28, 0x2c, 0x4c,
	0x19, 0x60, 0x65, 0x83, 0x0a, 0x09, 0x24, 0x86, 0x22, 0x1e, 0x20, 0x4d, 0xef, 0x60, 0xd4, 0xc6,
	0xc5, 0x76, 0x78, 0x53, 0xde, 0x07, 0xc9, 0x31, 0xa9, 0x8b, 0x33, 0xc1, 0x96, 0xfb, 0x93, 0xef,
	0x9c, 0x9c, 0x1b, 0x9c, 0x18, 0xd6, 0x9f, 0xb2, 0xe6, 0x72, 0xa7, 0x95, 0x55, 0x94, 0x55, 0x75,
	0xad, 0xda, 0xc6, 0x16, 0x0a, 0xb3, 0x7b, 0xcd, 0x95, 0xe5, 0x37, 0xc3, 0x7a, 0xc9, 0x1f, 0x2d,
	0x1b, 0x4b, 0x67, 0x98, 0x48, 0x63, 0x5a, 0xd6, 0x22, 0xb9, 0x4c, 0xae, 0x8f, 0x97, 0xbe, 0x22,
	0x81, 0xcc, 0xb4, 0xab, 0x77, 0xae, 0xad, 0x48, 0xdd, 0xe0, 0xa7, 0x24, 0xc2, 0xb8, 0xa9, 0xb6,
	0x2c, 0x46, 0xae, 0xed, 0x9e, 0x69, 0x8e, 0x23, 0xde, 0x56, 0x72, 0x23, 0xc6, 0xae, 0xd9, 0x15,
	0xc5, 0x0b, 0x28, 0x14, 0x34, 0x3b, 0xd5, 0x18, 0xa6, 0x29, 0x52, 0xb9, 0xf6, 0x6a, 0xa9, 0x5c,
	0xf7, 0xbc, 0x74, 0x88, 0x37, 0x0a, 0x79, 0x4f, 0x98, 0x3e, 0xb2, 0x0d, 0xdd, 0xff, 0x9d, 0xf5,
	0x8c, 0xd3, 0x9e, 0xf5, 0x6f, 0x63, 0x57, 0x98, 0x3d, 0xf0, 0x86, 0x0f, 0x93, 0xfd, 0x85, 0x2b,
	0xe6, 0xa0, 0x70, 0xa9, 0x13, 0xbd, 0xf9, 0x4a, 0x90, 0xbd, 0x76, 0xf7, 0xa2, 0x05, 0xb0, 0xcf,
	0x8b, 0xf2, 0xd2, 0x1f, 0xae, 0x8c, 0xae, 0x96, 0x5f, 0x0c, 0xce, 0xfc, 0x77, 0x2c, 0x80, 0xbd,
	0x50, 0x80, 0x89, 0x2c, 0x06, 0x98, 0xd8, 0x19, 0xdd, 0x21, 0xf3, 0x09, 0xd1, 0x79, 0xbf, 0x77,
	0x98, 0x7f, 0x2e, 0xe2, 0x41, 0xf7, 0xf6, 0x6a, 0xe2, 0x7e, 0xbe, 0xdb, 0xef, 0x00, 0x00, 0x00,
	0xff, 0xff, 0x11, 0x60, 0x2a, 0xae, 0x8d, 0x02, 0x00, 0x00,
}
