// Code generated by protoc-gen-go.
// source: service.proto
// DO NOT EDIT!

/*
Package project is a generated protocol buffer package.

It is generated from these files:
	service.proto

It has these top-level messages:
	Workflow
	Project
	CreateProjectRequest
	CreateProjectResponse
	UpdateProjectRequest
	UpdateProjectResponse
	UpdateWorkflowRequest
	UpdateWorkflowResponse
	DeleteProjectRequest
	DeleteProjectResponse
	GetProjectRequest
	GetProjectResponse
	ListProjectsRequest
	ListProjectsResponse
*/
package project

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Workflow struct {
	Source   string `protobuf:"bytes,1,opt,name=source" json:"source,omitempty"`
	Modified int64  `protobuf:"varint,2,opt,name=modified" json:"modified,omitempty"`
}

func (m *Workflow) Reset()                    { *m = Workflow{} }
func (m *Workflow) String() string            { return proto.CompactTextString(m) }
func (*Workflow) ProtoMessage()               {}
func (*Workflow) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Workflow) GetSource() string {
	if m != nil {
		return m.Source
	}
	return ""
}

func (m *Workflow) GetModified() int64 {
	if m != nil {
		return m.Modified
	}
	return 0
}

type Project struct {
	Id          string    `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Account     string    `protobuf:"bytes,2,opt,name=account" json:"account,omitempty"`
	Name        string    `protobuf:"bytes,3,opt,name=name" json:"name,omitempty"`
	Description string    `protobuf:"bytes,4,opt,name=description" json:"description,omitempty"`
	Created     int64     `protobuf:"varint,5,opt,name=created" json:"created,omitempty"`
	Modified    int64     `protobuf:"varint,6,opt,name=modified" json:"modified,omitempty"`
	Workflow    *Workflow `protobuf:"bytes,7,opt,name=workflow" json:"workflow,omitempty"`
}

func (m *Project) Reset()                    { *m = Project{} }
func (m *Project) String() string            { return proto.CompactTextString(m) }
func (*Project) ProtoMessage()               {}
func (*Project) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Project) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Project) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

func (m *Project) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Project) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Project) GetCreated() int64 {
	if m != nil {
		return m.Created
	}
	return 0
}

func (m *Project) GetModified() int64 {
	if m != nil {
		return m.Modified
	}
	return 0
}

func (m *Project) GetWorkflow() *Workflow {
	if m != nil {
		return m.Workflow
	}
	return nil
}

type CreateProjectRequest struct {
	Account     string `protobuf:"bytes,1,opt,name=account" json:"account,omitempty"`
	Name        string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Description string `protobuf:"bytes,3,opt,name=description" json:"description,omitempty"`
}

func (m *CreateProjectRequest) Reset()                    { *m = CreateProjectRequest{} }
func (m *CreateProjectRequest) String() string            { return proto.CompactTextString(m) }
func (*CreateProjectRequest) ProtoMessage()               {}
func (*CreateProjectRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *CreateProjectRequest) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

func (m *CreateProjectRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CreateProjectRequest) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

type CreateProjectResponse struct {
	Project *Project `protobuf:"bytes,1,opt,name=project" json:"project,omitempty"`
}

func (m *CreateProjectResponse) Reset()                    { *m = CreateProjectResponse{} }
func (m *CreateProjectResponse) String() string            { return proto.CompactTextString(m) }
func (*CreateProjectResponse) ProtoMessage()               {}
func (*CreateProjectResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *CreateProjectResponse) GetProject() *Project {
	if m != nil {
		return m.Project
	}
	return nil
}

type UpdateProjectRequest struct {
	Account     string `protobuf:"bytes,1,opt,name=account" json:"account,omitempty"`
	Id          string `protobuf:"bytes,2,opt,name=id" json:"id,omitempty"`
	Name        string `protobuf:"bytes,3,opt,name=name" json:"name,omitempty"`
	Description string `protobuf:"bytes,4,opt,name=description" json:"description,omitempty"`
}

func (m *UpdateProjectRequest) Reset()                    { *m = UpdateProjectRequest{} }
func (m *UpdateProjectRequest) String() string            { return proto.CompactTextString(m) }
func (*UpdateProjectRequest) ProtoMessage()               {}
func (*UpdateProjectRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *UpdateProjectRequest) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

func (m *UpdateProjectRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *UpdateProjectRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UpdateProjectRequest) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

type UpdateProjectResponse struct {
}

func (m *UpdateProjectResponse) Reset()                    { *m = UpdateProjectResponse{} }
func (m *UpdateProjectResponse) String() string            { return proto.CompactTextString(m) }
func (*UpdateProjectResponse) ProtoMessage()               {}
func (*UpdateProjectResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

type UpdateWorkflowRequest struct {
	Account string `protobuf:"bytes,1,opt,name=account" json:"account,omitempty"`
	Id      string `protobuf:"bytes,2,opt,name=id" json:"id,omitempty"`
	Source  string `protobuf:"bytes,3,opt,name=source" json:"source,omitempty"`
}

func (m *UpdateWorkflowRequest) Reset()                    { *m = UpdateWorkflowRequest{} }
func (m *UpdateWorkflowRequest) String() string            { return proto.CompactTextString(m) }
func (*UpdateWorkflowRequest) ProtoMessage()               {}
func (*UpdateWorkflowRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *UpdateWorkflowRequest) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

func (m *UpdateWorkflowRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *UpdateWorkflowRequest) GetSource() string {
	if m != nil {
		return m.Source
	}
	return ""
}

type UpdateWorkflowResponse struct {
}

func (m *UpdateWorkflowResponse) Reset()                    { *m = UpdateWorkflowResponse{} }
func (m *UpdateWorkflowResponse) String() string            { return proto.CompactTextString(m) }
func (*UpdateWorkflowResponse) ProtoMessage()               {}
func (*UpdateWorkflowResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

type DeleteProjectRequest struct {
	Account string `protobuf:"bytes,1,opt,name=account" json:"account,omitempty"`
	Id      string `protobuf:"bytes,2,opt,name=id" json:"id,omitempty"`
}

func (m *DeleteProjectRequest) Reset()                    { *m = DeleteProjectRequest{} }
func (m *DeleteProjectRequest) String() string            { return proto.CompactTextString(m) }
func (*DeleteProjectRequest) ProtoMessage()               {}
func (*DeleteProjectRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *DeleteProjectRequest) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

func (m *DeleteProjectRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type DeleteProjectResponse struct {
}

func (m *DeleteProjectResponse) Reset()                    { *m = DeleteProjectResponse{} }
func (m *DeleteProjectResponse) String() string            { return proto.CompactTextString(m) }
func (*DeleteProjectResponse) ProtoMessage()               {}
func (*DeleteProjectResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

type GetProjectRequest struct {
	Account string `protobuf:"bytes,1,opt,name=account" json:"account,omitempty"`
	Id      string `protobuf:"bytes,2,opt,name=id" json:"id,omitempty"`
}

func (m *GetProjectRequest) Reset()                    { *m = GetProjectRequest{} }
func (m *GetProjectRequest) String() string            { return proto.CompactTextString(m) }
func (*GetProjectRequest) ProtoMessage()               {}
func (*GetProjectRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *GetProjectRequest) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

func (m *GetProjectRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type GetProjectResponse struct {
	Project *Project `protobuf:"bytes,1,opt,name=project" json:"project,omitempty"`
}

func (m *GetProjectResponse) Reset()                    { *m = GetProjectResponse{} }
func (m *GetProjectResponse) String() string            { return proto.CompactTextString(m) }
func (*GetProjectResponse) ProtoMessage()               {}
func (*GetProjectResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

func (m *GetProjectResponse) GetProject() *Project {
	if m != nil {
		return m.Project
	}
	return nil
}

type ListProjectsRequest struct {
	Account string `protobuf:"bytes,1,opt,name=account" json:"account,omitempty"`
}

func (m *ListProjectsRequest) Reset()                    { *m = ListProjectsRequest{} }
func (m *ListProjectsRequest) String() string            { return proto.CompactTextString(m) }
func (*ListProjectsRequest) ProtoMessage()               {}
func (*ListProjectsRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{12} }

func (m *ListProjectsRequest) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

type ListProjectsResponse struct {
	Projects []*Project `protobuf:"bytes,1,rep,name=projects" json:"projects,omitempty"`
}

func (m *ListProjectsResponse) Reset()                    { *m = ListProjectsResponse{} }
func (m *ListProjectsResponse) String() string            { return proto.CompactTextString(m) }
func (*ListProjectsResponse) ProtoMessage()               {}
func (*ListProjectsResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{13} }

func (m *ListProjectsResponse) GetProjects() []*Project {
	if m != nil {
		return m.Projects
	}
	return nil
}

func init() {
	proto.RegisterType((*Workflow)(nil), "project.Workflow")
	proto.RegisterType((*Project)(nil), "project.Project")
	proto.RegisterType((*CreateProjectRequest)(nil), "project.CreateProjectRequest")
	proto.RegisterType((*CreateProjectResponse)(nil), "project.CreateProjectResponse")
	proto.RegisterType((*UpdateProjectRequest)(nil), "project.UpdateProjectRequest")
	proto.RegisterType((*UpdateProjectResponse)(nil), "project.UpdateProjectResponse")
	proto.RegisterType((*UpdateWorkflowRequest)(nil), "project.UpdateWorkflowRequest")
	proto.RegisterType((*UpdateWorkflowResponse)(nil), "project.UpdateWorkflowResponse")
	proto.RegisterType((*DeleteProjectRequest)(nil), "project.DeleteProjectRequest")
	proto.RegisterType((*DeleteProjectResponse)(nil), "project.DeleteProjectResponse")
	proto.RegisterType((*GetProjectRequest)(nil), "project.GetProjectRequest")
	proto.RegisterType((*GetProjectResponse)(nil), "project.GetProjectResponse")
	proto.RegisterType((*ListProjectsRequest)(nil), "project.ListProjectsRequest")
	proto.RegisterType((*ListProjectsResponse)(nil), "project.ListProjectsResponse")
}

func init() { proto.RegisterFile("service.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 480 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x55, 0x51, 0x6f, 0xd3, 0x30,
	0x10, 0x56, 0x92, 0xd1, 0x74, 0x57, 0x3a, 0xb1, 0xa3, 0x1b, 0x56, 0x60, 0x10, 0xf9, 0xa9, 0x42,
	0x50, 0xa4, 0xf2, 0x0c, 0x9a, 0xb4, 0x21, 0x1e, 0x40, 0x13, 0x04, 0x21, 0xc4, 0x63, 0x49, 0x5c,
	0xc9, 0xb0, 0xc5, 0x21, 0x4e, 0xb7, 0x7f, 0xc9, 0x6f, 0xe0, 0xa7, 0xa0, 0x39, 0x8e, 0xeb, 0x64,
	0x8e, 0x50, 0xf3, 0x56, 0xfb, 0xee, 0xbe, 0xfb, 0xbe, 0xbb, 0xcf, 0x0d, 0x4c, 0x25, 0x2b, 0xaf,
	0x79, 0xca, 0x16, 0x45, 0x29, 0x2a, 0x81, 0x61, 0x51, 0x8a, 0x9f, 0x2c, 0xad, 0xe8, 0x5b, 0x18,
	0x7f, 0x13, 0xe5, 0xaf, 0xf5, 0xa5, 0xb8, 0xc1, 0x63, 0x18, 0x49, 0xb1, 0x29, 0x53, 0x46, 0xbc,
	0xd8, 0x9b, 0xef, 0x27, 0xfa, 0x84, 0x11, 0x8c, 0xaf, 0x44, 0xc6, 0xd7, 0x9c, 0x65, 0xc4, 0x8f,
	0xbd, 0x79, 0x90, 0x98, 0x33, 0xfd, 0xe3, 0x41, 0xf8, 0xa9, 0xc6, 0xc2, 0x03, 0xf0, 0x79, 0xa6,
	0x6b, 0x7d, 0x9e, 0x21, 0x81, 0x70, 0x95, 0xa6, 0x62, 0x93, 0x57, 0xaa, 0x6c, 0x3f, 0x69, 0x8e,
	0x88, 0xb0, 0x97, 0xaf, 0xae, 0x18, 0x09, 0xd4, 0xb5, 0xfa, 0x8d, 0x31, 0x4c, 0x32, 0x26, 0xd3,
	0x92, 0x17, 0x15, 0x17, 0x39, 0xd9, 0x53, 0x21, 0xfb, 0xea, 0x16, 0x2f, 0x2d, 0xd9, 0xaa, 0x62,
	0x19, 0xb9, 0xa7, 0x68, 0x34, 0xc7, 0x16, 0xc3, 0x51, 0x9b, 0x21, 0xbe, 0x84, 0xf1, 0x8d, 0x56,
	0x48, 0xc2, 0xd8, 0x9b, 0x4f, 0x96, 0x87, 0x0b, 0xad, 0x7e, 0xd1, 0x48, 0x4f, 0x4c, 0x0a, 0x5d,
	0xc3, 0xec, 0x4c, 0xa1, 0x6a, 0x55, 0x09, 0xfb, 0xbd, 0x61, 0xb2, 0xb2, 0xc5, 0x78, 0x6e, 0x31,
	0x7e, 0xbf, 0x98, 0xe0, 0x8e, 0x18, 0x7a, 0x06, 0x47, 0x9d, 0x3e, 0xb2, 0x10, 0xb9, 0x64, 0xf8,
	0x1c, 0x9a, 0xe5, 0xa8, 0x46, 0x93, 0xe5, 0x03, 0x43, 0xb7, 0x49, 0x35, 0xdb, 0xbb, 0x86, 0xd9,
	0xd7, 0x22, 0xdb, 0x85, 0x6c, 0xbd, 0x23, 0xdf, 0xec, 0x68, 0xd0, 0x26, 0xe8, 0x23, 0x38, 0xea,
	0xf4, 0xad, 0xc9, 0xd3, 0xef, 0x4d, 0xc0, 0x4c, 0x76, 0x67, 0x46, 0x5b, 0x17, 0x06, 0xb6, 0x0b,
	0x29, 0x81, 0xe3, 0x2e, 0xb4, 0x6e, 0x7a, 0x0a, 0xb3, 0x73, 0x76, 0xc9, 0x86, 0x4f, 0xe1, 0x56,
	0x4f, 0x07, 0x41, 0x43, 0xbf, 0x81, 0xc3, 0xf7, 0xac, 0x1a, 0x8c, 0x7b, 0x0a, 0x68, 0x97, 0x0f,
	0xd8, 0xf0, 0x2b, 0x78, 0xf8, 0x91, 0xcb, 0x06, 0x42, 0xfe, 0x97, 0x02, 0x3d, 0x87, 0x59, 0xbb,
	0x40, 0x37, 0x7d, 0x01, 0x63, 0x8d, 0x29, 0x89, 0x17, 0x07, 0xce, 0xae, 0x26, 0x63, 0xf9, 0x37,
	0x80, 0xf0, 0x4b, 0xfd, 0x8f, 0x81, 0x17, 0x30, 0x6d, 0x39, 0x15, 0x4f, 0x4c, 0xa1, 0xeb, 0xa5,
	0x44, 0x4f, 0xfb, 0xc2, 0x9a, 0xc9, 0x3b, 0x80, 0xed, 0x50, 0x30, 0x32, 0xd9, 0x77, 0x06, 0x1d,
	0x3d, 0x76, 0xc6, 0x34, 0xcc, 0x07, 0xb8, 0x6f, 0x0b, 0xc5, 0x27, 0x26, 0xd9, 0x31, 0xb0, 0xe8,
	0xa4, 0x27, 0xaa, 0xc1, 0x2e, 0x60, 0xda, 0x32, 0xb4, 0xa5, 0xd1, 0xf5, 0xc0, 0x2c, 0x8d, 0xce,
	0x77, 0x80, 0x9f, 0xe1, 0xa0, 0x6d, 0x56, 0xec, 0x56, 0x74, 0x1e, 0x48, 0xf4, 0xac, 0x37, 0xbe,
	0xa5, 0xd8, 0xf2, 0xa8, 0x45, 0xd1, 0xe5, 0x7e, 0x8b, 0xa2, 0xd3, 0xda, 0x3f, 0x46, 0xea, 0x4b,
	0xf0, 0xfa, 0x5f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xff, 0x9b, 0x5d, 0x14, 0x1a, 0x06, 0x00, 0x00,
}
