// Code generated by protoc-gen-go.
// source: service.proto
// DO NOT EDIT!

/*
Package project is a generated protocol buffer package.

It is generated from these files:
	service.proto

It has these top-level messages:
	Node
	Workflow
	Project
	CreateProjectRequest
	CreateProjectResponse
	UpdateProjectRequest
	UpdateProjectResponse
	UpdateWorkflowRequest
	UpdateWorkflowResponse
	DeleteProjectRequest
	DeleteProjectResponse
	GetProjectRequest
	GetProjectResponse
	ListProjectsRequest
	ListProjectsResponse
*/
package project

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Node struct {
	Title  string   `protobuf:"bytes,1,opt,name=title" json:"title,omitempty"`
	Type   string   `protobuf:"bytes,2,opt,name=type" json:"type,omitempty"`
	Input  []string `protobuf:"bytes,3,rep,name=input" json:"input,omitempty"`
	Output []string `protobuf:"bytes,4,rep,name=output" json:"output,omitempty"`
}

func (m *Node) Reset()                    { *m = Node{} }
func (m *Node) String() string            { return proto.CompactTextString(m) }
func (*Node) ProtoMessage()               {}
func (*Node) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Node) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Node) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Node) GetInput() []string {
	if m != nil {
		return m.Input
	}
	return nil
}

func (m *Node) GetOutput() []string {
	if m != nil {
		return m.Output
	}
	return nil
}

type Workflow struct {
	Source   string           `protobuf:"bytes,1,opt,name=source" json:"source,omitempty"`
	Modified int64            `protobuf:"varint,2,opt,name=modified" json:"modified,omitempty"`
	Nodes    map[string]*Node `protobuf:"bytes,3,rep,name=nodes" json:"nodes,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
}

func (m *Workflow) Reset()                    { *m = Workflow{} }
func (m *Workflow) String() string            { return proto.CompactTextString(m) }
func (*Workflow) ProtoMessage()               {}
func (*Workflow) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Workflow) GetSource() string {
	if m != nil {
		return m.Source
	}
	return ""
}

func (m *Workflow) GetModified() int64 {
	if m != nil {
		return m.Modified
	}
	return 0
}

func (m *Workflow) GetNodes() map[string]*Node {
	if m != nil {
		return m.Nodes
	}
	return nil
}

type Project struct {
	Id          string    `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Account     string    `protobuf:"bytes,2,opt,name=account" json:"account,omitempty"`
	Name        string    `protobuf:"bytes,3,opt,name=name" json:"name,omitempty"`
	Description string    `protobuf:"bytes,4,opt,name=description" json:"description,omitempty"`
	Created     int64     `protobuf:"varint,5,opt,name=created" json:"created,omitempty"`
	Modified    int64     `protobuf:"varint,6,opt,name=modified" json:"modified,omitempty"`
	Workflow    *Workflow `protobuf:"bytes,7,opt,name=workflow" json:"workflow,omitempty"`
}

func (m *Project) Reset()                    { *m = Project{} }
func (m *Project) String() string            { return proto.CompactTextString(m) }
func (*Project) ProtoMessage()               {}
func (*Project) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Project) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Project) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

func (m *Project) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Project) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Project) GetCreated() int64 {
	if m != nil {
		return m.Created
	}
	return 0
}

func (m *Project) GetModified() int64 {
	if m != nil {
		return m.Modified
	}
	return 0
}

func (m *Project) GetWorkflow() *Workflow {
	if m != nil {
		return m.Workflow
	}
	return nil
}

type CreateProjectRequest struct {
	Account     string `protobuf:"bytes,1,opt,name=account" json:"account,omitempty"`
	Name        string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Description string `protobuf:"bytes,3,opt,name=description" json:"description,omitempty"`
}

func (m *CreateProjectRequest) Reset()                    { *m = CreateProjectRequest{} }
func (m *CreateProjectRequest) String() string            { return proto.CompactTextString(m) }
func (*CreateProjectRequest) ProtoMessage()               {}
func (*CreateProjectRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *CreateProjectRequest) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

func (m *CreateProjectRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CreateProjectRequest) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

type CreateProjectResponse struct {
	Project *Project `protobuf:"bytes,1,opt,name=project" json:"project,omitempty"`
}

func (m *CreateProjectResponse) Reset()                    { *m = CreateProjectResponse{} }
func (m *CreateProjectResponse) String() string            { return proto.CompactTextString(m) }
func (*CreateProjectResponse) ProtoMessage()               {}
func (*CreateProjectResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *CreateProjectResponse) GetProject() *Project {
	if m != nil {
		return m.Project
	}
	return nil
}

type UpdateProjectRequest struct {
	Account     string `protobuf:"bytes,1,opt,name=account" json:"account,omitempty"`
	Id          string `protobuf:"bytes,2,opt,name=id" json:"id,omitempty"`
	Name        string `protobuf:"bytes,3,opt,name=name" json:"name,omitempty"`
	Description string `protobuf:"bytes,4,opt,name=description" json:"description,omitempty"`
}

func (m *UpdateProjectRequest) Reset()                    { *m = UpdateProjectRequest{} }
func (m *UpdateProjectRequest) String() string            { return proto.CompactTextString(m) }
func (*UpdateProjectRequest) ProtoMessage()               {}
func (*UpdateProjectRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *UpdateProjectRequest) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

func (m *UpdateProjectRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *UpdateProjectRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UpdateProjectRequest) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

type UpdateProjectResponse struct {
}

func (m *UpdateProjectResponse) Reset()                    { *m = UpdateProjectResponse{} }
func (m *UpdateProjectResponse) String() string            { return proto.CompactTextString(m) }
func (*UpdateProjectResponse) ProtoMessage()               {}
func (*UpdateProjectResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

type UpdateWorkflowRequest struct {
	Account string `protobuf:"bytes,1,opt,name=account" json:"account,omitempty"`
	Id      string `protobuf:"bytes,2,opt,name=id" json:"id,omitempty"`
	Source  string `protobuf:"bytes,3,opt,name=source" json:"source,omitempty"`
}

func (m *UpdateWorkflowRequest) Reset()                    { *m = UpdateWorkflowRequest{} }
func (m *UpdateWorkflowRequest) String() string            { return proto.CompactTextString(m) }
func (*UpdateWorkflowRequest) ProtoMessage()               {}
func (*UpdateWorkflowRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *UpdateWorkflowRequest) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

func (m *UpdateWorkflowRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *UpdateWorkflowRequest) GetSource() string {
	if m != nil {
		return m.Source
	}
	return ""
}

type UpdateWorkflowResponse struct {
}

func (m *UpdateWorkflowResponse) Reset()                    { *m = UpdateWorkflowResponse{} }
func (m *UpdateWorkflowResponse) String() string            { return proto.CompactTextString(m) }
func (*UpdateWorkflowResponse) ProtoMessage()               {}
func (*UpdateWorkflowResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

type DeleteProjectRequest struct {
	Account string `protobuf:"bytes,1,opt,name=account" json:"account,omitempty"`
	Id      string `protobuf:"bytes,2,opt,name=id" json:"id,omitempty"`
}

func (m *DeleteProjectRequest) Reset()                    { *m = DeleteProjectRequest{} }
func (m *DeleteProjectRequest) String() string            { return proto.CompactTextString(m) }
func (*DeleteProjectRequest) ProtoMessage()               {}
func (*DeleteProjectRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *DeleteProjectRequest) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

func (m *DeleteProjectRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type DeleteProjectResponse struct {
}

func (m *DeleteProjectResponse) Reset()                    { *m = DeleteProjectResponse{} }
func (m *DeleteProjectResponse) String() string            { return proto.CompactTextString(m) }
func (*DeleteProjectResponse) ProtoMessage()               {}
func (*DeleteProjectResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

type GetProjectRequest struct {
	Account string `protobuf:"bytes,1,opt,name=account" json:"account,omitempty"`
	Id      string `protobuf:"bytes,2,opt,name=id" json:"id,omitempty"`
}

func (m *GetProjectRequest) Reset()                    { *m = GetProjectRequest{} }
func (m *GetProjectRequest) String() string            { return proto.CompactTextString(m) }
func (*GetProjectRequest) ProtoMessage()               {}
func (*GetProjectRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

func (m *GetProjectRequest) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

func (m *GetProjectRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type GetProjectResponse struct {
	Project *Project `protobuf:"bytes,1,opt,name=project" json:"project,omitempty"`
}

func (m *GetProjectResponse) Reset()                    { *m = GetProjectResponse{} }
func (m *GetProjectResponse) String() string            { return proto.CompactTextString(m) }
func (*GetProjectResponse) ProtoMessage()               {}
func (*GetProjectResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{12} }

func (m *GetProjectResponse) GetProject() *Project {
	if m != nil {
		return m.Project
	}
	return nil
}

type ListProjectsRequest struct {
	Account string `protobuf:"bytes,1,opt,name=account" json:"account,omitempty"`
}

func (m *ListProjectsRequest) Reset()                    { *m = ListProjectsRequest{} }
func (m *ListProjectsRequest) String() string            { return proto.CompactTextString(m) }
func (*ListProjectsRequest) ProtoMessage()               {}
func (*ListProjectsRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{13} }

func (m *ListProjectsRequest) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

type ListProjectsResponse struct {
	Projects []*Project `protobuf:"bytes,1,rep,name=projects" json:"projects,omitempty"`
}

func (m *ListProjectsResponse) Reset()                    { *m = ListProjectsResponse{} }
func (m *ListProjectsResponse) String() string            { return proto.CompactTextString(m) }
func (*ListProjectsResponse) ProtoMessage()               {}
func (*ListProjectsResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{14} }

func (m *ListProjectsResponse) GetProjects() []*Project {
	if m != nil {
		return m.Projects
	}
	return nil
}

func init() {
	proto.RegisterType((*Node)(nil), "project.Node")
	proto.RegisterType((*Workflow)(nil), "project.Workflow")
	proto.RegisterType((*Project)(nil), "project.Project")
	proto.RegisterType((*CreateProjectRequest)(nil), "project.CreateProjectRequest")
	proto.RegisterType((*CreateProjectResponse)(nil), "project.CreateProjectResponse")
	proto.RegisterType((*UpdateProjectRequest)(nil), "project.UpdateProjectRequest")
	proto.RegisterType((*UpdateProjectResponse)(nil), "project.UpdateProjectResponse")
	proto.RegisterType((*UpdateWorkflowRequest)(nil), "project.UpdateWorkflowRequest")
	proto.RegisterType((*UpdateWorkflowResponse)(nil), "project.UpdateWorkflowResponse")
	proto.RegisterType((*DeleteProjectRequest)(nil), "project.DeleteProjectRequest")
	proto.RegisterType((*DeleteProjectResponse)(nil), "project.DeleteProjectResponse")
	proto.RegisterType((*GetProjectRequest)(nil), "project.GetProjectRequest")
	proto.RegisterType((*GetProjectResponse)(nil), "project.GetProjectResponse")
	proto.RegisterType((*ListProjectsRequest)(nil), "project.ListProjectsRequest")
	proto.RegisterType((*ListProjectsResponse)(nil), "project.ListProjectsResponse")
}

func init() { proto.RegisterFile("service.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 587 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x55, 0xdd, 0x6e, 0xd3, 0x4c,
	0x10, 0x95, 0xed, 0xfc, 0x7d, 0x93, 0x2f, 0x55, 0x3b, 0xa4, 0xc5, 0x32, 0x14, 0x22, 0x73, 0x83,
	0x10, 0x04, 0x29, 0xdc, 0x20, 0x24, 0xa4, 0x4a, 0x6d, 0xd5, 0x0b, 0x50, 0x04, 0x46, 0x08, 0x71,
	0x83, 0x14, 0xec, 0x8d, 0xb4, 0x34, 0xf5, 0x1a, 0xef, 0x3a, 0x55, 0x9e, 0x8d, 0x77, 0xe0, 0x19,
	0x78, 0x14, 0xb4, 0xeb, 0xf5, 0xfa, 0x27, 0x8e, 0x50, 0x73, 0xe7, 0xd9, 0x99, 0x3d, 0x73, 0xce,
	0xd9, 0xd9, 0x35, 0x8c, 0x38, 0x49, 0xd7, 0x34, 0x24, 0xd3, 0x24, 0x65, 0x82, 0x61, 0x3f, 0x49,
	0xd9, 0x0f, 0x12, 0x0a, 0xff, 0x1b, 0x74, 0xe6, 0x2c, 0x22, 0x38, 0x86, 0xae, 0xa0, 0x62, 0x45,
	0x5c, 0x6b, 0x62, 0x3d, 0xfd, 0x2f, 0xc8, 0x03, 0x44, 0xe8, 0x88, 0x4d, 0x42, 0x5c, 0x5b, 0x2d,
	0xaa, 0x6f, 0x59, 0x49, 0xe3, 0x24, 0x13, 0xae, 0x33, 0x71, 0x64, 0xa5, 0x0a, 0xf0, 0x04, 0x7a,
	0x2c, 0x13, 0x72, 0xb9, 0xa3, 0x96, 0x75, 0xe4, 0xff, 0xb2, 0x60, 0xf0, 0x85, 0xa5, 0xd7, 0xcb,
	0x15, 0xbb, 0x95, 0x45, 0x9c, 0x65, 0x69, 0x58, 0x74, 0xd1, 0x11, 0x7a, 0x30, 0xb8, 0x61, 0x11,
	0x5d, 0x52, 0x12, 0xa9, 0x56, 0x4e, 0x60, 0x62, 0x9c, 0x41, 0x37, 0x66, 0x11, 0xe1, 0xaa, 0xdd,
	0x70, 0xf6, 0x70, 0xaa, 0x99, 0x4f, 0x0b, 0xd4, 0xa9, 0xe4, 0xcf, 0x2f, 0x63, 0x91, 0x6e, 0x82,
	0xbc, 0xd4, 0xbb, 0x02, 0x28, 0x17, 0xf1, 0x10, 0x9c, 0x6b, 0xb2, 0xd1, 0x2d, 0xe5, 0x27, 0x3e,
	0x81, 0xee, 0x7a, 0xb1, 0xca, 0x72, 0x5d, 0xc3, 0xd9, 0xc8, 0x60, 0xca, 0x5d, 0x41, 0x9e, 0x7b,
	0x63, 0xbf, 0xb6, 0xfc, 0xdf, 0x16, 0xf4, 0x3f, 0xe4, 0x39, 0x3c, 0x00, 0x9b, 0x46, 0x1a, 0xc5,
	0xa6, 0x11, 0xba, 0xd0, 0x5f, 0x84, 0x21, 0xcb, 0x62, 0xa1, 0xed, 0x29, 0x42, 0xe9, 0x5a, 0xbc,
	0xb8, 0x21, 0xae, 0x93, 0xbb, 0x26, 0xbf, 0x71, 0x02, 0xc3, 0x88, 0xf0, 0x30, 0xa5, 0x89, 0xa0,
	0x2c, 0x76, 0x3b, 0x2a, 0x55, 0x5d, 0x92, 0x78, 0x61, 0x4a, 0x16, 0x82, 0x44, 0x6e, 0x57, 0x79,
	0x50, 0x84, 0x35, 0x7b, 0x7a, 0x0d, 0x7b, 0x5e, 0xc0, 0xe0, 0x56, 0x1b, 0xe1, 0xf6, 0x95, 0x9a,
	0xa3, 0x2d, 0x87, 0x02, 0x53, 0xe2, 0x2f, 0x61, 0x7c, 0xae, 0x50, 0xb5, 0xaa, 0x80, 0xfc, 0xcc,
	0x08, 0x17, 0x55, 0x31, 0x56, 0xbb, 0x18, 0x7b, 0xb7, 0x18, 0x67, 0x4b, 0x8c, 0x7f, 0x0e, 0xc7,
	0x8d, 0x3e, 0x3c, 0x61, 0x31, 0x27, 0xf8, 0x0c, 0x8a, 0xd1, 0x53, 0x8d, 0x86, 0xb3, 0x43, 0x43,
	0xb7, 0x28, 0x35, 0xb3, 0xb9, 0x86, 0xf1, 0xe7, 0x24, 0xba, 0x0b, 0xd9, 0xfc, 0x8c, 0x6c, 0x73,
	0x46, 0x7b, 0x9d, 0x84, 0x7f, 0x1f, 0x8e, 0x1b, 0x7d, 0x73, 0xf2, 0xfe, 0xd7, 0x22, 0x61, 0x9c,
	0xbd, 0x33, 0xa3, 0xf2, 0x0a, 0x38, 0xd5, 0x2b, 0xe0, 0xbb, 0x70, 0xd2, 0x84, 0xd6, 0x4d, 0xcf,
	0x60, 0x7c, 0x41, 0x56, 0x64, 0x7f, 0x17, 0xa4, 0x9e, 0x06, 0x82, 0x86, 0x7e, 0x0b, 0x47, 0x57,
	0x44, 0xec, 0x8d, 0x7b, 0x06, 0x58, 0xdd, 0xbe, 0xc7, 0x09, 0xbf, 0x84, 0x7b, 0xef, 0x29, 0x2f,
	0x20, 0xf8, 0x3f, 0x29, 0xf8, 0x17, 0x30, 0xae, 0x6f, 0xd0, 0x4d, 0x9f, 0xc3, 0x40, 0x63, 0x72,
	0xd7, 0x52, 0x0f, 0xc5, 0x76, 0x57, 0x53, 0x31, 0xfb, 0xe3, 0x40, 0xff, 0x53, 0xfe, 0x1e, 0xe2,
	0x1c, 0x46, 0xb5, 0x49, 0xc5, 0x53, 0xb3, 0xb1, 0xed, 0xa6, 0x78, 0x8f, 0x76, 0xa5, 0x35, 0x93,
	0x4b, 0x80, 0xd2, 0x14, 0xf4, 0x4c, 0xf5, 0x96, 0xd1, 0xde, 0x83, 0xd6, 0x9c, 0x86, 0x79, 0x07,
	0xff, 0x57, 0x85, 0x62, 0xf9, 0xee, 0xb5, 0x18, 0xe6, 0x9d, 0xee, 0xc8, 0x6a, 0xb0, 0x39, 0x8c,
	0x6a, 0x03, 0x5d, 0xd1, 0xd8, 0x76, 0xc1, 0x2a, 0x1a, 0x5b, 0xef, 0x01, 0x7e, 0x84, 0x83, 0xfa,
	0xb0, 0x62, 0x73, 0x47, 0xe3, 0x82, 0x78, 0x8f, 0x77, 0xe6, 0x4b, 0x8a, 0xb5, 0x19, 0xad, 0x50,
	0x6c, 0x9b, 0xfe, 0x0a, 0xc5, 0xd6, 0xd1, 0xfe, 0xde, 0x53, 0xff, 0xb9, 0x57, 0x7f, 0x03, 0x00,
	0x00, 0xff, 0xff, 0x9a, 0x26, 0x81, 0x25, 0xf8, 0x06, 0x00, 0x00,
}
